export const constructorsImages = {
    'ferrari': require('../assets/constructorsChampionsImages/scuderiaFerrari.png'),
    'williams': require('../assets/constructorsChampionsImages/williams.png'),
    'mclaren': require('../assets/constructorsChampionsImages/mclaren.png'),
    'mercedes': require('../assets/constructorsChampionsImages/mercedes.jpeg'),
    'team_lotus': require('../assets/constructorsChampionsImages/lotus.png'),
    'lotus-climax': require('../assets/constructorsChampionsImages/lotus.png'),
    'lotus-ford': require('../assets/constructorsChampionsImages/lotus.png'),
    'red_bull': require('../assets/constructorsChampionsImages/redbull.png'),
    'cooper-climax': require('../assets/constructorsChampionsImages/cooper.png'),
    'brabham-repco': require('../assets/constructorsChampionsImages/brabham.png'),
    'renault': require('../assets/constructorsChampionsImages/renault.png'),
    'vanwall': require('../assets/constructorsChampionsImages/vanwall.jpg'),
    'brm': require('../assets/constructorsChampionsImages/brm.png'),
    'matra-ford': require('../assets/constructorsChampionsImages/matra.png'),
    'tyrrell': require('../assets/constructorsChampionsImages/tyrrell.png'),
    'benetton': require('../assets/constructorsChampionsImages/benetton.png'),
    'brawn': require('../assets/constructorsChampionsImages/brawn.png'),
}