export const currentDriversSideImage = {
    "max_verstappen": require("../assets/currentDriversSideImages/verstappen.jpg"),
    "perez": require("../assets/currentDriversSideImages/perez.jpg"),
    "leclerc": require("../assets/currentDriversSideImages/leclerc.jpg"),
    "sainz": require("../assets/currentDriversSideImages/sainz.jpg"),
    "hamilton": require("../assets/currentDriversSideImages/hamilton.jpg"),
    "russell": require("../assets/currentDriversSideImages/russell.jpg"),
    "alonso": require("../assets/currentDriversSideImages/alonso.jpg"),
    "stroll": require("../assets/currentDriversSideImages/stroll.jpg"),
    "ocon": require("../assets/currentDriversSideImages/ocon.jpg"),
    "gasly": require("../assets/currentDriversSideImages/gasly.jpg"),
    "norris": require("../assets/currentDriversSideImages/norris.jpg"),
    "piastri": require("../assets/currentDriversSideImages/piastri.jpg"),
    "albon": require("../assets/currentDriversSideImages/albon.jpg"),
    "sargeant": require("../assets/currentDriversSideImages/sargeant.jpg"),
    "hulkenberg": require("../assets/currentDriversSideImages/hulkenberg.jpg"),
    "kevin_magnussen": require("../assets/currentDriversSideImages/magnussen.jpg"),
    "bottas": require("../assets/currentDriversSideImages/bottas.jpg"),
    "zhou": require("../assets/currentDriversSideImages/zhou.jpg"),
    "tsunoda": require("../assets/currentDriversSideImages/tsunoda.jpg"),
    "ricciardo": require("../assets/currentDriversSideImages/ricciardo.jpg"),
    "bearman" : require("../assets/currentDriversSideImages/bearman.jpg"),
}