export const currentDrivers = {
    "albon" : require("../assets/currentDriversImages/albon.jpg"),
    "alonso" : require("../assets/currentDriversImages/alonso.jpg"),
    "bottas" : require("../assets/currentDriversImages/bottas.jpg"),
    "de_vries" : require("../assets/currentDriversImages/de_vries.jpg"),
    "gasly" : require("../assets/currentDriversImages/gasly.jpg"),
    "hamilton" : require("../assets/currentDriversImages/hamilton.jpg"),
    "hulkenberg" : require("../assets/currentDriversImages/hulkenberg.jpg"),
    "leclerc" : require("../assets/currentDriversImages/leclerc.jpg"),
    "kevin_magnussen" : require("../assets/currentDriversImages/magnussen.jpg"),
    "norris" : require("../assets/currentDriversImages/norris.jpg"),
    "ocon" : require("../assets/currentDriversImages/ocon.jpg"),
    "perez" : require("../assets/currentDriversImages/perez.jpg"),
    "piastri" : require("../assets/currentDriversImages/piastri.jpg"),
    "ricciardo" : require("../assets/currentDriversImages/ricciardo.jpg"),
    "russell" : require("../assets/currentDriversImages/russell.jpg"),
    "sainz" : require("../assets/currentDriversImages/sainz.jpg"),
    "sargeant" : require("../assets/currentDriversImages/sargeant.jpg"),
    "stroll" : require("../assets/currentDriversImages/stroll.jpg"),
    "tsunoda" : require("../assets/currentDriversImages/tsunoda.jpg"),
    "max_verstappen" : require("../assets/currentDriversImages/verstappen.jpg"),
    "zhou" : require("../assets/currentDriversImages/zhou.jpg"),
}