export const currentDriversTeam = {
    "max_verstappen": "Red Bull",
    "perez": "Red Bull",
    "leclerc": "Ferrari",
    "sainz": "Ferrari",
    "hamilton": "Mercedes",
    "russell": "Mercedes",
    "alonso": "Aston Martin",
    "stroll": "Aston Martin",
    "ocon": "Alpine",
    "gasly": "Alpine",
    "norris": "McLaren",
    "piastri": "McLaren",
    "albon": "Williams",
    "sargeant": "Williams",
    "hulkenberg": "Haas",
    "kevin_magnussen": "Haas",
    "bottas": "Alfa Romeo",
    "zhou": "Alfa Romeo",
    "tsunoda": "AlphaTauri",
    "ricciardo": "AlphaTauri",
    "de_vries": "AlphaTauri",
}