export const currentYearTracks = {
    "bahrain": require("../assets/currentYearTracks/bahrain.png"),
    "jeddah": require("../assets/currentYearTracks/jeddah.png"),
    "albert_park": require("../assets/currentYearTracks/albert_park.png"),
    "baku": require("../assets/currentYearTracks/baku.png"),
    "miami": require("../assets/currentYearTracks/miami.png"),
    "monaco": require("../assets/currentYearTracks/monaco.png"),
    "catalunya": require("../assets/currentYearTracks/catalunya.png"),
    "villeneuve": require("../assets/currentYearTracks/villeneuve.png"),
    "red_bull_ring": require("../assets/currentYearTracks/red_bull_ring.png"),
    "silverstone": require("../assets/currentYearTracks/silverstone.png"),
    "hungaroring": require("../assets/currentYearTracks/hungaroring.png"),
    "spa": require("../assets/currentYearTracks/spa.png"),
    "zandvoort": require("../assets/currentYearTracks/zandvoort.png"),
    "monza": require("../assets/currentYearTracks/monza.png"),
    "marina_bay": require("../assets/currentYearTracks/marina_bay.png"),
    "suzuka": require("../assets/currentYearTracks/suzuka.png"),
    "losail": require("../assets/currentYearTracks/losail.png"),
    "americas": require("../assets/currentYearTracks/americas.png"),
    "rodriguez": require("../assets/currentYearTracks/rodriguez.png"),
    "interlagos": require("../assets/currentYearTracks/interlagos.png"),
    "vegas": require("../assets/currentYearTracks/vegas.png"),
    "yas_marina": require("../assets/currentYearTracks/yas_marina.png"),
}