export const currentDriversTeamId = {
    "max_verstappen": "red_bull",
    "perez": "red_bull",
    "leclerc": "ferrari",
    "sainz": "ferrari",
    "hamilton": "mercedes",
    "russell": "mercedes",
    "alonso": "aston_martin",
    "stroll": "aston_martin",
    "ocon": "alpine",
    "gasly": "alpine",
    "norris": "mclaren",
    "piastri": "mclaren",
    "albon": "williams",
    "sargeant": "williams",
    "hulkenberg": "haas",
    "kevin_magnussen": "haas",
    "bottas": "sauber",
    "zhou": "sauber",
    "tsunoda": "rb",
    "ricciardo": "rb",
    "bearman": "ferrari",
}