export const flagsNationality = {
    "American": require("../assets/countryFlags/usa.jpg"),
    "Argentine": require("../assets/countryFlags/argentina.jpg"),
    "Australian": require("../assets/countryFlags/australia.jpg"),
    "Austrian": require("../assets/countryFlags/austria.jpg"),
    "Brazilian": require("../assets/countryFlags/brazil.jpg"),
    "British": require("../assets/countryFlags/uk.jpg"),
    "Canadian": require("../assets/countryFlags/canada.jpg"),
    "Chinese": require("../assets/countryFlags/china.png"),
    "Danish": require("../assets/countryFlags/denmark.png"),
    "Dutch": require("../assets/countryFlags/netherlands.jpg"),
    "German": require("../assets/countryFlags/germany.jpg"),
    "Finnish": require("../assets/countryFlags/finland.jpg"),
    "French": require("../assets/countryFlags/france.png"),
    "Italian": require("../assets/countryFlags/italy.jpg"),
    "Japanese": require("../assets/countryFlags/japan.jpg"),
    "Mexican": require("../assets/countryFlags/mexico.jpg"),
    "Monegasque": require("../assets/countryFlags/monaco.jpg"),
    "New Zealander": require("../assets/countryFlags/newZealand.jpg"),
    "South African": require("../assets/countryFlags/southAfrica.jpg"),
    "Spanish": require("../assets/countryFlags/spain.jpg"),
    "Swiss" : require("../assets/countryFlags/switzerland.jpg"),
    "Thai": require("../assets/countryFlags/thailand.png"),
}