export const flagsNationality = {
    "American": require("../assets/countryFlags/usa.jpg"),
    "American-Italian" : require("../assets/countryFlags/usa.jpg"),
    "Argentine": require("../assets/countryFlags/argentina.jpg"),
    "Argentine-Italian": require('../assets/countryFlags/argentina.jpg'),
    "Australian": require("../assets/countryFlags/australia.jpg"),
    "Austrian": require("../assets/countryFlags/austria.jpg"),
    "Belgian": require("../assets/countryFlags/belgium.jpg"),
    "Brazilian": require("../assets/countryFlags/brazil.jpg"),
    "British": require("../assets/countryFlags/uk.jpg"),
    "Canadian": require("../assets/countryFlags/canada.jpg"),
    "Chilean": require("../assets/countryFlags/chile.png"),
    "Chinese": require("../assets/countryFlags/china.png"),
    "Colombian": require("../assets/countryFlags/colombia.png"),
    "Czech": require("../assets/countryFlags/czech.png"),
    "Danish": require("../assets/countryFlags/denmark.png"),
    "Dutch": require("../assets/countryFlags/netherlands.jpg"),
    "East German": require("../assets/countryFlags/eastGermany.png"),
    "Finnish": require("../assets/countryFlags/finland.jpg"),
    "French": require("../assets/countryFlags/france.png"),
    "German": require("../assets/countryFlags/germany.jpg"),
    "Hungarian": require("../assets/countryFlags/hungary.jpg"),
    "Indian": require("../assets/countryFlags/india.jpg"),
    "Indonesian": require("../assets/countryFlags/indonesia.png"),
    "Irish": require("../assets/countryFlags/ireland.png"),
    "Italian": require("../assets/countryFlags/italy.jpg"),
    "Japanese": require("../assets/countryFlags/japan.jpg"),
    "Liechtensteiner": require("../assets/countryFlags/liechtenstein.png"),
    "Malaysian": require("../assets/countryFlags/malaysia.jpg"),
    "Mexican": require("../assets/countryFlags/mexico.jpg"),
    "Monegasque": require("../assets/countryFlags/monaco.jpg"),
    "New Zealander": require("../assets/countryFlags/newZealand.jpg"),
    "Polish": require("../assets/countryFlags/poland.png"),
    "Portuguese": require("../assets/countryFlags/portugal.jpg"),
    "Rhodesian": require("../assets/countryFlags/rhodesia.png"),
    "Russian": require("../assets/countryFlags/russia.jpg"),
    "South African": require("../assets/countryFlags/southAfrica.jpg"),
    "Spanish": require("../assets/countryFlags/spain.jpg"),
    "Swedish": require("../assets/countryFlags/sweden.jpg"),
    "Swiss" : require("../assets/countryFlags/switzerland.jpg"),
    "Thai": require("../assets/countryFlags/thailand.png"),
    "Uruguayan": require("../assets/countryFlags/uruguay.png"),
    "Venezuelan": require("../assets/countryFlags/venezuela.png"),
}